import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { pool } from './pool.js';
import { env } from '../config/env.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const seedFile = path.resolve(__dirname, '../../../db/seeds/001_seed.sql');
const baseSql = fs.readFileSync(seedFile, 'utf8');
const sql = baseSql.replaceAll('__DEFAULT_ADMIN_EMAIL__', env.defaultAdminEmail).replaceAll('__DEFAULT_ADMIN_PASSWORD_HASH__', await bcrypt.hash(env.defaultAdminPassword, env.bcryptRounds));
await pool.query(sql);
await pool.end();
