import express from 'express';
import cors from 'cors';
import routes from './routes/index.js';
import { env } from './config/env.js';
import { errorHandler, notFoundHandler } from './middleware/errorHandler.js';
export const app = express();
app.use(cors({ origin: env.corsOrigin }));
app.use(express.json());
app.use(routes);
app.use(notFoundHandler);
app.use(errorHandler);
