import { Router } from 'express';
import healthRoutes from './healthRoutes.js';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import creditRoutes from './creditRoutes.js';
import sessionRoutes from './sessionRoutes.js';
import bookingRoutes from './bookingRoutes.js';
const router = Router();
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/credits', creditRoutes);
router.use('/sessions', sessionRoutes);
router.use('/bookings', bookingRoutes);
export default router;
